//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.tblDocuments = new HashSet<tblDocument>();
            this.tblPropertyValues = new HashSet<tblPropertyValue>();
        }
    
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public string Product_Series { get; set; }
        public string Product_Model { get; set; }
        public System.DateTime Product_Model_Year { get; set; }
        public string Product_Series_Info { get; set; }
        public Nullable<bool> Product_Featured { get; set; }
        public int SubCat_Id { get; set; }
        public int Manuf_Id { get; set; }
    
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        public virtual tblManufacture tblManufacture { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
        public virtual ICollection<tblPropertyValue> tblPropertyValues { get; set; }
    }
}
